services:
  postgres:
    image: postgres:17
    container_name: pulsepass-db
    environment:
      POSTGRES_DB: pulsepass
      POSTGRES_USER: pulsepass
      POSTGRES_PASSWORD: pulsepass
    ports:
      - "5432:5432"
    volumes:
      - pulsepass-data:/var/lib/postgresql/data

volumes:
  pulsepass-data: