spring.application.name=pulsepass

spring.datasource.url=jdbc:postgresql://localhost:5432/pulsepass
spring.datasource.username=pulsepass
spring.datasource.password=pulsepass

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true